### ISSUE TITLE
[FE][FEAT] 매칭 로딩, 결과 페이지 제작

### ISSUE THREAD

**Issue by SeyeonJang** [COMAtching/COMAtching_FE#79]
## 💻 Feature 설명
> 매칭 로딩, 결과 페이지 제작
<br>

## 📝 To-do
**match_load_page**
- [x] 로딩 색 & 애니메이션 수정
- [x] text, box 사이즈 및 위치 조정

**result_page**
- [x] Pc 스크린을 모바일로 변경
- [x] 목업 데이터 추가, Content 내용 순서 조정, 애니메이션 변경
- [x] 취미 아이템 추가 (아이콘 포함)
- [x] 실데이터 연결 로직 추가

<br>
## 🖥️ 이전 화면

![스크린샷 2024-09-05 오전 12 36 06](https://github.com/user-attachments/assets/c993966a-e57c-484a-9969-0ca80fbbca39)
![스크린샷 2024-09-05 오전 12 39 58](https://github.com/user-attachments/assets/ca6f7795-34b4-4f60-a307-068a6702d18b)

<br>
## 📸 스크린샷

https://github.com/user-attachments/assets/6d95e323-6254-4734-b2a9-dba394099084

https://github.com/user-attachments/assets/94d68a55-329e-42e0-a093-ecf0a6a5ba3c
